project:
  type: website
  output-dir: docs
  
website:
  title: "My Portfolio"
  search: false
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "My Resume"
        href: about.qmd
      - text: "Statistical Software"
        href: software.qmd
    sidebar: false
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    backgroundcolor: "lightgrey"
#    fontcolor: "magenta"
#    linkcolor: "darkgreen"
#    mainfont: "sarif"
#    max-width: (width of the main text area of the pages)
#    fontsize: (base font size for website)
#    linestretch: (distance between lines of text)
    theme: cosmo
    toc: true

editor: source

